# Generated by Django 6.1.1 on 2026-09-05 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMotivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('motivation_type', models.CharField(default='affirmation', max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motivations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='meditation', max_length=100)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('duration_minutes', models.IntegerField(default=5)),
                ('video_url', models.CharField(blank=True, max_length=500)),
                ('video_type', models.CharField(default='youtube', max_length=20)),
                ('thumbnail_image', models.CharField(blank=True, max_length=500)),
                ('instructions', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('is_guided', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', 'display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('entry_type', models.CharField(choices=[('reflection', 'Reflection'), ('gratitude', 'Gratitude'), ('goal', 'Goal'), ('dream', 'Dream'), ('creative', 'Creative'), ('daily_log', 'Daily Log'), ('free_write', 'Free Write')], default='reflection', max_length=30)),
                ('mood', models.CharField(blank=True, max_length=50)),
                ('mood_before', models.CharField(blank=True, max_length=50)),
                ('mood_after', models.CharField(blank=True, max_length=50)),
                ('energy_level', models.IntegerField(default=5)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('is_private', models.BooleanField(default=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('word_count', models.IntegerField(default=0)),
                ('gratitude_list', models.TextField(blank=True)),
                ('goals', models.TextField(blank=True)),
                ('dreams_notes', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('weather', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_score', models.IntegerField(default=5)),
                ('primary_emotion', models.CharField(blank=True, max_length=100)),
                ('secondary_emotion', models.CharField(blank=True, max_length=100)),
                ('stress_level', models.IntegerField(default=5)),
                ('energy_level', models.IntegerField(default=5)),
                ('sleep_quality', models.IntegerField(default=3)),
                ('triggers_factors', models.TextField(blank=True)),
                ('gratitude', models.TextField(blank=True)),
                ('journal_entry', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelationshipEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('relationship_type', models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('partner', 'Partner'), ('colleague', 'Colleague'), ('other', 'Other')], max_length=50)),
                ('interaction_quality', models.IntegerField(default=5)),
                ('emotional_energy', models.CharField(choices=[('energizing', 'Energizing'), ('neutral', 'Neutral'), ('draining', 'Draining')], default='neutral', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('mood_before', models.IntegerField(blank=True, null=True)),
                ('mood_after', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserExerciseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=True)),
                ('mood_before', models.IntegerField(default=5)),
                ('mood_after', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='wellness.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WellnessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(max_length=50)),
                ('target_value', models.IntegerField()),
                ('current_value', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
