# Generated by Django 6.1.1 on 2026-09-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='thumbnail_file',
            field=models.ImageField(blank=True, upload_to='exercises/thumbnails/'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_file',
            field=models.FileField(blank=True, upload_to='exercises/videos/'),
        ),
    ]
