# Generated by Django 6.1.1 on 2026-09-26 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0002_exercise_thumbnail_file_exercise_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload an MP4, WebM, OGV, or MOV video.', upload_to='exercises/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogv', 'mov'])]),
        ),
    ]
