# Generated by Django 6.1.1 on 2026-09-26 10:43

import django.db.models.deletion
from django.db import migrations, models


def publish_existing_exercises(apps, schema_editor):
    Exercise = apps.get_model('wellness', 'Exercise')
    Exercise.objects.filter(published_at__isnull=True).update(published_at=models.F('created_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_communitypost_moderation_status_and_more'),
        ('wellness', '0003_alter_exercise_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='media_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practices', to='community.mediaasset'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=12),
        ),
        migrations.RunPython(publish_existing_exercises, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='exercise',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=12),
        ),
    ]
