# Generated by Django 6.1.1 on 2026-09-26 10:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0004_exercise_media_asset_exercise_published_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexercisesession',
            name='progress_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userexercisesession',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
