# Generated by Django 6.1.1 on 2026-09-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0005_userexercisesession_progress_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('breathing', 'Breathing'), ('meditation', 'Meditation'), ('yoga_flow', 'Yoga Flow'), ('grounding', 'Grounding'), ('yoga', 'Yoga Flow'), ('mindfulness', 'Grounding')], default='meditation', max_length=100),
        ),
    ]
