# Generated by Django 6.1.1 on 2026-09-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymouschatsession',
            name='topic',
            field=models.CharField(blank=True, default='General Support', max_length=80),
        ),
    ]
